### ISSUE TITLE
Click action on logo, should redirect user to the landing page

### ISSUE THREAD

**Issue by gaurangkeluskar22** [Chinmay2660/MovieSphere#27]
**Issue:**
Click action on the logo, should redirect the user to the landing page

**Demo:**

https://github.com/user-attachments/assets/b5213592-bf2d-4dd3-a54b-d4028b5d650e

**Comment by gaurangkeluskar22** [comment]
Hi @Chinmay2660 , can you please assign this issue to me.

**Comment by Chinmay2660** [comment]
@gaurangkeluskar22 Assigned you!

**Comment by gaurangkeluskar22** [comment]
Hi @Chinmay2660 , Added PR https://github.com/Chinmay2660/MovieSphere/pull/28 please review the PR.
